In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns



A = np.array([[7, 6], [2, 5+2]])
print(A)

shape = np.shape(A)
print(shape)

# Finding Determinant
det_a = np.linalg.det(A)
print(det_a)

# Finding Inverse when Det>0
if det_a != 0:
  inv_matrix = np.linalg.inv(A)
else:
  inv_matrix = "Impossible"

print(inv_matrix)

# Finding Rank
rank = np.linalg.matrix_rank(A)
print(rank)

# Eigenvalues
eigenvalues = np.linalg.eig(A)
print(eigenvalues)




# Matrix B (changed one value)
# Changed (2,2) position: 7 → 8

B = np.array([[7, 6], [2, 5+3]])
print(B)


# Finding shape
shape = np.shape(B)
print(shape)

# Finding Determinant
det_b = np.linalg.det(B)
print(det_b)

# Finding Inverse when Det>0
if det_b != 0:
  inv_matrix = np.linalg.inv(B)
else:
  inv_matrix = "Impossible"

print(inv_matrix)

# Finding Rank
rank = np.linalg.matrix_rank(B)
print(rank)

# Eigenvalues
eigenvalues = np.linalg.eig(B)
print(eigenvalues)



[[7 6]
 [2 7]]
(2, 2)
36.99999999999999
[[ 0.18918919 -0.16216216]
 [-0.05405405  0.18918919]]
2
EigResult(eigenvalues=array([10.46410162,  3.53589838]), eigenvectors=array([[ 0.8660254, -0.8660254],
       [ 0.5      ,  0.5      ]]))
[[7 6]
 [2 8]]
(2, 2)
43.99999999999999
[[ 0.18181818 -0.13636364]
 [-0.04545455  0.15909091]]
2
EigResult(eigenvalues=array([ 4., 11.]), eigenvectors=array([[-0.89442719, -0.83205029],
       [ 0.4472136 , -0.5547002 ]]))


In [ ]:
# Answer -> 01
# Determinant changed because we modified a diagonal value.
# For A: det = 37
# For B: det = 44
# Increasing the bottom-right element increased the product ad in (ad - bc),
# so the determinant increased.


# Answer -> 02
# Rank did not change.
# Since determinant ≠ 0 for both matrices,
# both matrices remain full rank (rank = 2).


# Answer -> 03
# Eigenvalues shifted upward.
# The sum of eigenvalues equals the trace.
# Trace increased from 14 to 15,
# so eigenvalue sum increased accordingly.


# Answer -> 04
# Matrix B is easier to invert.
# Its determinant (44) is larger than A's (37),
# meaning it is further from singularity and more numerically stable.